config/routes.rb
Kakeibo3::Application.routes.draw do

  root :to => "login#login"

  match 'simple', :to => 'entries#new', :entry_type => 'simple', :as => 'simple_input'
  match 'login' => 'login#login', :as => :login
  match 'logout' => 'login#do_logout', :as => :logout
  
  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  resources :entries, :path_prefix => 'current', :as => 'current_entries'
  resources :profit_losses, :path_prefix => 'current',:as => 'current_profit_losses'
  resources :balance_sheets, :path_prefix => 'current', :as => 'current_balance_sheets'
  
  tag_base = '/tags/:tag'
  resources :entries, :path_prefix => tag_base, :as => 'tag_entries'
  mark_base = '/marks/:mark'
  resources :entries, :path_prefix => mark_base, :as => 'mark_entries'

  resources :entries do
    resource :confirmation_required
  end
  
  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

    
  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :assets
    resources :budgets
    scope ':year_month' do
      resources :entries
    end
  end
  
  match ':controller(/:action(/:id(.:format)))'
end

app/models/credit_relation.rb
# -*- coding: utf-8 -*-
class CreditRelation < ActiveRecord::Base
	validate :validate_everytime
	validates_uniqueness_of   :credit_account_id
	validates_numericality_of :credit_account_id
	validates_numericality_of :payment_account_id
	validates_inclusion_of :payment_month, :in=>0..3

	def validate_everytime
		if settlement_day < 1 || (settlement_day > 28 && settlement_day != 99)
			errors.add(:settlement_day, "が不正な値です。")
		end
		if payment_day < 1 || (payment_day > 28 && payment_day != 99)
			errors.add(:payment_day, "が不正な値です。")
		end
		# 引き落としが同月で締め日が引き落とし日より大きい場合はエラー
		if payment_month == 0 && payment_day < settlement_day
			errors.add("settlement_day", "引き落とし日は締め日後でなければなりません。")
		end
		# クレジットカードと引き落としが同じ場合はエラー
		if payment_account_id == credit_account_id
			errors.add("credit_account_id","クレジットカードと引き落とし口座は別でなければなりません。")
		end

	end
end

app/controllers/settings/accounts_controller.rb
# -*- coding: utf-8 -*-
class Settings::AccountsController < ApplicationController
  before_filter :required_login

 
  def index
    @account_type = params[:account_type].presence || 'account'
    unless ['account', 'outgo', 'income'].include?(@account_type)
      redirect_to login_url
      return
    end
    @accounts = @user.accounts.where(:account_type => @account_type).order(:order_no).all
    
    render :layout => 'entries'
  end

  def create
    @account = Account.new(:name => params[:account_name],
                           :order_no => params[:order_no],
                           :account_type => params[:account_type],
                           :user_id => @user.id)
    @account.save!
    redirect_rjs_to settings_accounts_url(:account_type => @account.account_type)
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "add_warning", :errors => @account.errors, :default_message => '入力値が不正です'
  end
  
  def edit
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end

  def update
    id  = params[:id]
    name  = params[:account_name]
    order_no  = params[:order_no]
    bgcolor = params[:use_bgcolor] == '1' ?  params[:bgcolor].presence : nil

    @account = @user.accounts.find(id)
    @account.update_attributes!(:name => name, :order_no => order_no, :bgcolor => bgcolor)
    redirect_rjs_to settings_accounts_url(:account_type => @account.account_type)

  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "account_#{@account.id}_warning", :errors => @account.errors, :default_message => '入力値が不正です', :before => "$('edit_button_#{@account.id}').disabled = false"
  end

  def destroy
    id = params[:id]
    account = @user.accounts.find(id)

    item = @user.items.where("from_account_id = ? or to_account_id = ?", id, id).first
    if item
      render_rjs_error :id => "add_warning", :default_message => "すでに収支情報に使用されているため、削除できません。" + 
        item.action_date.strftime("%Y/%m/%d") + " " + item.name + " " + 
        CommonUtil.separate_by_comma(item.amount) + "円"
      return
    end

    credit_rel = @user.credit_relations.where("credit_account_id = ? or payment_account_id = ?", id, id).first
    if credit_rel
      render_rjs_error :id => "add_warning", :default_message => "クレジットカード支払い情報に関連づけられているため、削除できません。"
      return
    end
    account.destroy
    @account = account
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end
  
  def show
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end
end

app/controllers/settings/credit_relations_controller.rb
# -*- coding: utf-8 -*-
class Settings::CreditRelationsController < ApplicationController
  before_filter :required_login
  before_filter :set_separated_accounts, :only => [:update, :show, :index, :edit, :destroy, :create]
  
  def index
    @credit_relations = @user.credit_relations.all
    render :action=>'index', :layout=>'entries'
  end
  
  def create
    @cr = @user.credit_relations.create(:credit_account_id => params[:credit_account_id].to_i,
                                         :payment_account_id => params[:payment_account_id].to_i,
                                         :settlement_day => params[:settlement_day].to_i,
                                         :payment_month => params[:payment_month].to_i,
                                         :payment_day => params[:payment_day].to_i)

    if @cr.errors.empty?
      @credit_relations = @user.credit_relations.all
      render
    else
      render_rjs_error :id => "warning", :errors => @cr.errors, :default_message => 'Error!!'
    end
  end
  
  def destroy
    @user.credit_relations.destroy(params[:id])
    @destroyed_id = params[:id]
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render "no_record.rjs"
  end
  
  def edit
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_rjs_error :id => "warning", :default_errors => "データが存在しません。"
  end
  
  def update
    @cr = @user.credit_relations.find(params[:id])
    @cr.update_attributes!(:credit_account_id => params[:credit_account_id].to_i,
                           :payment_account_id => params[:payment_account_id].to_i,
                           :settlement_day => params[:settlement_day].to_i,
                           :payment_month => params[:payment_month].to_i,
                           :payment_day => params[:payment_day].to_i)
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render "no_record.rjs"
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "edit_warning_#{@cr.id}", :errors => @cr.errors, :default_message => 'Error!!', :before => "Element.update('warning', '');"
  end
  
  def show
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to settings_credit_relations_url
  end
end

app/controllers/settings/users_controller.rb
# -*- coding: utf-8 -*-
class Settings::UsersController < ApplicationController
  before_filter :required_login

  def show
    render :layout => 'entries'
  end
  
  def update
    user_to_change = User.find(@user.id)
    user_to_change.email = params[:email]
    user_to_change.password_plain = params[:password_plain]
    user_to_change.password_confirmation = params[:password_confirmation]

    @user_to_change = user_to_change
    user_to_change.save!
    @user = user_to_change
    session[:user_id] = @user.id
  rescue ActiveRecord::RecordInvalid => ex
    render_rjs_error :id => "warning", :errors => @user_to_change.errors, :default_message => _('Input value is incorrect')
  end
  
end

app/helpers/config/credit_relations_helper.rb
module Config::CreditRelationsHelper
end

app/views/settings/credit_relations/_edit.html.erb
<div id="credit_relation_<%= @cr.id %>">
<%= form_tag settings_credit_relation_path(@cr.id), :remote => true, :method => :put, :before => "$('edit_button_#{@cr.id}').disabled = true", :complete => "$('edit_button_#{@cr.id}').disabled = false" , :id => 'edit_form_#{@cr.id}' do %>
<table>
<tr><th>クレジットカード</th><th>引き落とし口座</th><th>締め日</th><th>引き落とし日</th><th>操作</th></tr>
<tr><td><%= select_tag 'credit_account_id', options_for_select(@separated_accounts[:bank_accounts], @cr.credit_account_id.to_s) %></td>
<td><%= select_tag 'payment_account_id', options_for_select(@separated_accounts[:bank_accounts], @cr.payment_account_id.to_s) %></td>
<td>毎月 <%= select_tag 'settlement_day', options_for_select(CREDIT_RELATION_SETTLEMENT_DAYS, @cr.settlement_day) %>日</td>
<td><%= select_tag 'payment_month', options_for_select(CREDIT_RELATION_PAYMENT_MONTHS, @cr.payment_month) %> <%= select_tag 'payment_day', options_for_select(CREDIT_RELATION_PAYMENT_DAYS, @cr.payment_day) %>日</td>
<td><%= submit_tag '変更', :id=>"edit_button_#{@cr.id}" %><br/><%= link_to 'キャンセル', settings_credit_relation_path(@cr.id), :remote => true, :method => :get %></td></tr>
</table>
<% end %>
<span id="edit_warning_<%= @cr.id %>" class="warning"></span>
</div>

app/views/settings/credit_relations/_show.html.erb
<div id="credit_relation_<%= cr.id %>">
<div class="cfg_credit_relation_name"><%=h @separated_accounts[:all_accounts][cr.credit_account_id] %></div>
<div class="cfg_payment_relation_name"><%=h @separated_accounts[:all_accounts][cr.payment_account_id] %></div>
<div class="cfg_settlement_day">毎月 <%=h (cr.settlement_day == 99) ? '末日' : cr.settlement_day.to_s + '日' %></div>
<div class="cfg_payment_date"><%= (
if cr.payment_month == 0 
	'同月'
elsif cr.payment_month == 1
	'翌月'
elsif cr.payment_month == 2
	'翌々月'
elsif cr.payment_month == 3
	'翌々々月'
end)
%> <%=h (cr.payment_day < 99) ? cr.payment_day.to_s + '日' : '末日' %></div>
<div class="cfg_credit_relation_operation"><%= link_to '編集', edit_settings_credit_relation_path(cr.id), :remote => true,  :method => :get %> <%= link_to '削除', settings_credit_relation_path(cr.id), :remote => true, :method => :delete, :confirm=>"本当に削除しますか?" %></div>
</div>
<div class="reset"></div>

app/views/settings/credit_relations/index.html.erb
<div id='menu'>
<%= render :partial=>'settings/config_menu' %>
</div>
<div class="cfg_credit_relation_list">
  <p>登録</p>
  <div>
    <%= form_tag settings_credit_relations_path, {:remote => true, :method => :post, :before => "$('add_button').disabled = true", :complete => "$('add_button').disabled = false", :id => 'add_form'} do %>
    <table>
      <tr>
	<th>クレジットカード</th><th>引き落とし口座</th><th>締め日</th><th>引き落とし日</th><th>操作</th>
      </tr>
      <tr>
	<td><%= select_tag 'credit_account_id', options_for_select(@separated_accounts[:bank_accounts]) %></td>
	<td><%= select_tag 'payment_account_id', options_for_select(@separated_accounts[:bank_accounts]) %></td>
	<td>毎月 <%= select_tag 'settlement_day', options_for_select(CREDIT_RELATION_SETTLEMENT_DAYS) %>日</td>
	<td><%= select_tag 'payment_month', options_for_select(CREDIT_RELATION_PAYMENT_MONTHS) %> <%= select_tag 'payment_day', options_for_select(CREDIT_RELATION_PAYMENT_DAYS) %>日</td>
	<td><%= submit_tag '登録', :id=>'add_button' %></td>
      </tr>
    </table>
    <% end %>
  </div>

  <div id="warning" class="warning"></div>
  <p>一覧/変更/削除</p>
  <div id="credit_relations_headers">
    <div class="cfg_credit_relation_name cfg_credit_relation_header">クレジットカード</div>
    <div class="cfg_payment_relation_name cfg_credit_relation_header">引き落とし口座</div>
    <div class="cfg_settlement_day cfg_credit_relation_header">締め日</div>
    <div class="cfg_payment_date cfg_credit_relation_header">引き落とし日</div>
    <div class="cfg_credit_relation_operation cfg_credit_relation_header">操作</div>
  </div>
  <div class="reset"></div>
  <div id="credit_relations">
    <% @credit_relations.each do |cr| %>
      <%= render :partial=> 'show', :locals => {:cr => cr} %>
    <% end %>
  </div>
</div>