config/routes.rb
Kakeibo3::Application.routes.draw do

  root :to => "login#login"

  match 'simple', :to => 'entries#new', :entry_type => 'simple', :as => 'simple_input'
  match 'login' => 'login#login', :as => :login
  match 'logout' => 'login#do_logout', :as => :logout
  
  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  resources :entries, :path_prefix => 'current', :as => 'current_entries'
  resources :profit_losses, :path_prefix => 'current',:as => 'current_profit_losses'
  resources :balance_sheets, :path_prefix => 'current', :as => 'current_balance_sheets'
  
  tag_base = '/tags/:tag'
  resources :entries, :path_prefix => tag_base, :as => 'tag_entries'
  mark_base = '/marks/:mark'
  resources :entries, :path_prefix => mark_base, :as => 'mark_entries'

  resources :entries do
    resource :confirmation_required
  end
  
  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

    
  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :assets
    resources :budgets
    scope ':year_month' do
      resources :entries
    end
  end
  
  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
# -*- coding: utf-8 -*-
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :accounts
  
	validates_presence_of :name
	validates_length_of :name, :in =>1..255
	validates_presence_of :order_no
	validates_format_of :order_no, :with => /^\d+$/
	validates_format_of :account_type, :with => /^account$|^income$|^outgo$/
	validates_format_of :bgcolor, :with => /^[0-9a-f]{6}/i, :allow_nil => true

  scope :active, where(:is_active => true)

	#
	# 残高を取得する
	# my_id でitemのIDを指定すると、そのItemが除外される。また、new_dateと、my_idに該当するitemのaction_dateが同一の場合、
	# new_dateと同じ日のitemデータのうち、my_idよりidがおおきいものは残高計算から除外する
	#
	def self.asset(user, account_id, new_date, my_id=nil) 

		date = new_date
		# amountの算出
		# 前月までのassetを算出
		asset = user.monthly_profit_losses.where(:account_id => account_id).months_before(new_date.beginning_of_month).sum("amount")

    my_item = my_id ? user.items.find_by_id(my_id) : nil

		# 今月のassetの変化を算出
		# 残高情報の新規登録の場合
    outgo_items = income_items = user.items
    
		if my_item.nil?
      outgo_items = outgo_items.action_date_between(date.beginning_of_month, date).where(:from_account_id => account_id)
      income_items = income_items.action_date_between(date.beginning_of_month, date).where(:to_account_id => account_id)
		else
			if  my_item.action_date == date
        outgo_items = outgo_items.where("(action_date >= ? and action_date < ?) or (action_date = ? and id < ?)", date.beginning_of_month, date, date, my_id).where(:from_account_id => account_id)
        income_items = income_items.where("(action_date >= ? and action_date < ?) or (action_date = ? and id < ?)", date.beginning_of_month, date, date, my_id).where(:to_account_id => account_id)
			else # 日付が変更になった場合
        outgo_items = outgo_items.action_date_between(date.beginning_of_month, date).where("id <> ?", my_id).where(:from_account_id => account_id)
        income_items = income_items.action_date_between(date.beginning_of_month, date).where("id <> ?", my_id).where(:to_account_id => account_id)
			end
		end

    outgo = outgo_items.sum("amount")
		income = income_items.sum("amount")
    outgo ||= 0
    income ||= 0
    
		asset += income - outgo

		#
		# 今月以前はplから抽出してしまうため、SQLではmy_item.amountを除外できない
		#
		if my_item && my_item.action_date < date.beginning_of_month
			if my_item.from_account_id == account_id
				asset += my_item.amount
			else
				asset -= my_item.amount
			end
		end

		return asset
	end
end

app/controllers/settings/accounts_controller.rb
# -*- coding: utf-8 -*-
class Settings::AccountsController < ApplicationController
  before_filter :required_login

 
  def index
    @account_type = params[:account_type].presence || 'account'
    unless ['account', 'outgo', 'income'].include?(@account_type)
      redirect_to login_url
      return
    end
    @accounts = @user.accounts.where(:account_type => @account_type).order(:order_no).all
    
    render :layout => 'entries'
  end

  def create
    @account = Account.new(:name => params[:account_name],
                           :order_no => params[:order_no],
                           :account_type => params[:account_type],
                           :user_id => @user.id)
    @account.save!
    redirect_rjs_to settings_accounts_url(:account_type => @account.account_type)
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "add_warning", :errors => @account.errors, :default_message => '入力値が不正です'
  end
  
  def edit
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end

  def update
    id  = params[:id]
    name  = params[:account_name]
    order_no  = params[:order_no]
    bgcolor = params[:use_bgcolor] == '1' ?  params[:bgcolor].presence : nil

    @account = @user.accounts.find(id)
    @account.update_attributes!(:name => name, :order_no => order_no, :bgcolor => bgcolor)
    redirect_rjs_to settings_accounts_url(:account_type => @account.account_type)

  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "account_#{@account.id}_warning", :errors => @account.errors, :default_message => '入力値が不正です', :before => "$('edit_button_#{@account.id}').disabled = false"
  end

  def destroy
    id = params[:id]
    account = @user.accounts.find(id)

    item = @user.items.where("from_account_id = ? or to_account_id = ?", id, id).first
    if item
      render_rjs_error :id => "add_warning", :default_message => "すでに収支情報に使用されているため、削除できません。" + 
        item.action_date.strftime("%Y/%m/%d") + " " + item.name + " " + 
        CommonUtil.separate_by_comma(item.amount) + "円"
      return
    end

    credit_rel = @user.credit_relations.where("credit_account_id = ? or payment_account_id = ?", id, id).first
    if credit_rel
      render_rjs_error :id => "add_warning", :default_message => "クレジットカード支払い情報に関連づけられているため、削除できません。"
      return
    end
    account.destroy
    @account = account
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end
  
  def show
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to login_url
  end
end

app/controllers/settings/credit_relations_controller.rb
# -*- coding: utf-8 -*-
class Settings::CreditRelationsController < ApplicationController
  before_filter :required_login
  before_filter :set_separated_accounts, :only => [:update, :show, :index, :edit, :destroy, :create]
  
  def index
    @credit_relations = @user.credit_relations.all
    render :action=>'index', :layout=>'entries'
  end
  
  def create
    @cr = @user.credit_relations.create(:credit_account_id => params[:credit_account_id].to_i,
                                         :payment_account_id => params[:payment_account_id].to_i,
                                         :settlement_day => params[:settlement_day].to_i,
                                         :payment_month => params[:payment_month].to_i,
                                         :payment_day => params[:payment_day].to_i)

    if @cr.errors.empty?
      @credit_relations = @user.credit_relations.all
      render
    else
      render_rjs_error :id => "warning", :errors => @cr.errors, :default_message => 'Error!!'
    end
  end
  
  def destroy
    @user.credit_relations.destroy(params[:id])
    @destroyed_id = params[:id]
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render "no_record.rjs"
  end
  
  def edit
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_rjs_error :id => "warning", :default_errors => "データが存在しません。"
  end
  
  def update
    @cr = @user.credit_relations.find(params[:id])
    @cr.update_attributes!(:credit_account_id => params[:credit_account_id].to_i,
                           :payment_account_id => params[:payment_account_id].to_i,
                           :settlement_day => params[:settlement_day].to_i,
                           :payment_month => params[:payment_month].to_i,
                           :payment_day => params[:payment_day].to_i)
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render "no_record.rjs"
  rescue ActiveRecord::RecordInvalid
    render_rjs_error :id => "edit_warning_#{@cr.id}", :errors => @cr.errors, :default_message => 'Error!!', :before => "Element.update('warning', '');"
  end
  
  def show
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_rjs_to settings_credit_relations_url
  end
end

app/controllers/settings/users_controller.rb
# -*- coding: utf-8 -*-
class Settings::UsersController < ApplicationController
  before_filter :required_login

  def show
    render :layout => 'entries'
  end
  
  def update
    user_to_change = User.find(@user.id)
    user_to_change.email = params[:email]
    user_to_change.password_plain = params[:password_plain]
    user_to_change.password_confirmation = params[:password_confirmation]

    @user_to_change = user_to_change
    user_to_change.save!
    @user = user_to_change
    session[:user_id] = @user.id
  rescue ActiveRecord::RecordInvalid => ex
    render_rjs_error :id => "warning", :errors => @user_to_change.errors, :default_message => _('Input value is incorrect')
  end
  
end

app/helpers/config/accounts_helper.rb
module Config::AccountsHelper
end

app/views/settings/accounts/_add.html.erb
<%= form_tag settings_accounts_path, :remote => true, :method => :post, :before=>"$('submit_button').disabled = true", :complete=>"$('submit_button').disabled = false" do -%>
<%= '口座名' if @account_type == 'account' %><%= '支出項目名' if @account_type == 'outgo' %><%= '収入項目名' if @account_type == 'income' %>:<%= text_field_tag :account_name, nil, :size=>20 %> 並順:<%= text_field_tag :order_no, nil, :size=>3 %><%= hidden_field_tag :account_type, @account_type -%>
<%= submit_tag '登録', :id=>"submit_button"  %>
<% end -%>
<div id="add_warning" class="warning"></div>

app/views/settings/accounts/_edit.html.erb
<div id="account_<%= @account.id.to_s %>">
<%= form_tag settings_account_path(@account.id), :method => :put, :remote => true,  :before=>"$('edit_button_#{@account.id.to_s}').disabled = true" do -%><%= text_field_tag :account_name, @account.name, :size=>20 %><%= text_field_tag :order_no, @account.order_no, :size=>3 %><%= submit_tag '保存', :id=>"edit_button_#{@account.id.to_s}" %> <%= link_to 'キャンセル', settings_account_path(@account.id), :remote => true, :method => :get -%>
<br/>背景色を利用<%= check_box_tag :use_bgcolor, '1', (not @account.bgcolor.nil?), :id => "use_bgcolor_#{@account.id.to_s}", :onchange => "if ($('use_bgcolor_#{@account.id.to_s}').checked) { $('colorbox_#{@account.id.to_s}').disabled = false;} else { $('colorbox_#{@account.id.to_s}').disabled = true;}" %><%= hidden_field_tag :bgcolor, @account.bgcolor.nil? ? '#ffffff' : @account.bgcolor, :id => "colorfield_#{@account.id}" %><button style="width: 1.5em; height: 1.2em; border: 1px outset #666;" id="colorbox_<%= @account.id.to_s %>" class="colorbox"></button><% end -%>
<br/><span id="account_<%= @account.id.to_s %>_warning" class="warning"></span>
</div>

app/views/settings/accounts/_show.html.erb
<div id="account_<%= account.id.to_s %>" class="cfg_account">
<div class="cfg_account_name"><% if account.bgcolor.blank? %><%=h account.name %><% else %><span style="background-color: #<%=h account.bgcolor %>;"><%=h account.name %></span><% end %></div>
<div class="cfg_account_order"><%= account.order_no %></div>
<div class="cfg_account_operation"><%= link_to '編集', edit_settings_account_path(account.id), :method => :get, :remote => true %> <%= link_to '削除', settings_account_path(account.id), :method => :delete, :confirm=>'本当に削除しますか?', :remote => true %></div>
</div>
<div class="reset"></div>

app/views/settings/accounts/index.html.erb
<%= javascript_include_tag 'builder' %>
<%= javascript_include_tag 'dragdrop' %>
<%= javascript_include_tag 'slider' %>
<%= javascript_include_tag 'yahoo.color' %>
<%= javascript_include_tag 'colorPicker' %>
<%= stylesheet_link_tag 'colorPicker' %>
<div id='menu'>
<%= render :partial=>'settings/config_menu' %>
</div>
<div class='cfg_account_list'>
<div id='input_add'>
<%= render :partial=>'add' %>
</div>

<div id="accounts">
<div class="cfg_account">
<div class="cfg_account_name cfg_account_header"><%= '口座名' if @account_type == 'account' %><%= '支出項目名' if @account_type == 'outgo' %><%= '収入項目名' if @account_type == 'income' %></div>
<div class="cfg_account_order cfg_account_header">並順</div>
<div class="cfg_account_operation cfg_account_header">&nbsp;</div>
</div>
<div class="reset"></div>
<% @accounts.each do |account| %>
<%= render :partial=>'show', :locals => {:account => account} -%>
<% end %>
</div>
</div>