config/routes.rb
Kakeibo3::Application.routes.draw do

  root :to => "login#login"

  match 'simple', :to => 'entries#new', :entry_type => 'simple', :as => 'simple_input'
  match 'login' => 'login#login', :as => :login
  match 'logout' => 'login#do_logout', :as => :logout
  
  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  resources :entries, :path_prefix => 'current', :as => 'current_entries'
  resources :profit_losses, :path_prefix => 'current',:as => 'current_profit_losses'
  resources :balance_sheets, :path_prefix => 'current', :as => 'current_balance_sheets'
  
  tag_base = '/tags/:tag'
  resources :entries, :path_prefix => tag_base, :as => 'tag_entries'
  mark_base = '/marks/:mark'
  resources :entries, :path_prefix => mark_base, :as => 'mark_entries'

  resources :entries do
    resource :confirmation_required
  end
  
  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

    
  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :assets
    resources :budgets
    scope ':year_month' do
      resources :entries
    end
  end
  
  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/api/entries_controller.rb
class Api::EntriesController < ApplicationController
  before_filter :required_login
  before_filter :valid_combined_month?
  respond_to :json

  def index
    date = Date.new(@year, @month)
    
    items = @user.items.where(:action_date => date.beginning_of_month..date.end_of_month).order("action_date desc, id desc")
    respond_with items.to_custom_hash.to_json
  end

  def show
    
  end

  def destroy
  end

  def update
    
  end

  private
  def valid_combined_month?
    if CommonUtil.valid_combined_year_month?(params[:year_month])
      @year, @month = CommonUtil.get_year_month_from_combined(params[:year_month])
    else
      redirect_to login_url
    end
  end
end

app/controllers/entries_controller.rb
# -*- coding: utf-8 -*-
class EntriesController < ApplicationController
  before_filter :required_login
  before_filter :set_separated_accounts, :only => [:index, :create, :update, :destroy, :new, :edit, :show]
  
  def index
    @tag = params[:tag]
    @mark = params[:mark]

    @display_year_month = _date_to_display(params[:year], params[:month])

    case
    when params[:remaining]
      _index_for_remaining(params[:year].to_i, params[:month].to_i, @tag, @mark)
    when !params[:filter_account_id].nil?
      _index_with_filter_account_id
    when @tag.present?
      _index_with_tag(@tag)
    when @mark.present?
      _index_with_mark(@mark)
    else
      _index_plain(@display_year_month)
    end
  rescue # 日付が不正の場合がある
    respond_to do |format|
      format.js {  redirect_rjs_to current_entries_url }
      format.html {  redirect_to current_entries_url }
    end
  end
  
  def _index_with_filter_account_id
    _set_filter_account_id_to_session_from_params
    @items = _get_items(@display_year_month.year, @display_year_month.month)
    render "index_with_filter_account_id.rjs"
  end
  
  def _index_with_tag(tag)
    @items = _get_items(nil, nil, false, tag, nil)
    render ('index_with_tag')
  end
  
  def _index_with_mark(mark)
    @items = _get_items(nil, nil, false, nil, mark)
    render ('index_with_mark')
  end
  
  def _default_action_date(month_to_display)
    month_to_display == today.beginning_of_month ? today : month_to_display
  end
  
  def _set_filter_account_id_to_session_from_params
    account_id = params[:filter_account_id].to_i
    session[:filter_account_id] = account_id == 0 ? nil : account_id
  end
      
  def _date_to_display(year, month)
    year.present? && month.present? ? Date.new(year.to_i, month.to_i) : today.beginning_of_month
  end
    
  
  def _index_plain(month_to_display)
    @items = _get_items(month_to_display.year, month_to_display.month)
    @new_item = Item.new { |item| item.action_date = _default_action_date(month_to_display) }
  end

  #
  # 支出、収入の登録入力
  #
  def new
    case params[:entry_type]
    when 'simple'
      _new_simple
    when 'adjustment'
      _new_adjustment
    else
      _new_entry
    end
  end
  
  def create
    if params[:entry_type] == 'adjustment'
      _create_adjustment
    else
      _create_entry
    end
  end
  
  def update
    return if _redirect_to_login_by_rjs_if_id_is_blank(params[:id])
    
    if params[:entry_type] == 'adjustment'
      _update_adjustment
    else
      _update_item
    end

  end

  def _redirect_to_login_by_rjs_if_id_is_blank(id)
    if id.blank?
      redirect_rjs_to login_url
      return true
    end
  end
  
  def destroy
    item = @user.items.find(params[:id])
    _destroy_item(item)
  rescue ActiveRecord::RecordNotFound => ex
    url = params[:id].blank? ? login_url : entries_url(today.year, today.month)
    redirect_rjs_to url
  end

  def _destroy_item(item)
    if item.is_adjustment?
      _destroy_adjustment(item)
    else
      _destroy_regular_item(item)
    end
  end
  #
  # アイテムの編集領域の表示
  #
  def edit
    @item = @user.items.find(params[:id])
  rescue ActiveRecord::RecordNotFound => ex
    redirect_rjs_to entries_url(:year => today.year, :month => today.month)
  end
  
  #
  # replace an input field with a regular text
  #
  def show
    @item = @user.items.find(params[:id])
  rescue ActiveRecord::RecordNotFound => ex
    redirect_rjs_to current_entries_url
  end


  private
  #### PRIVATE ###########
  # 収支の登録
  def _new_entry
    item = Item.new
    if params[:year].blank? || params[:month].blank? || today.beginning_of_month == Date.new(params[:year].to_i, params[:month].to_i)
      item.action_date = today
    else
      item.action_date = Date.new(params[:year].to_i, params[:month].to_i)
    end

    @item = item
    render "add_item.rjs"
  end

  #
  # 残高調整の登録入力
  #
  def _new_adjustment
    @action_date = _get_date_by_specific_year_and_month_or_today(params[:year], params[:month])
    render "add_adjustment.rjs"
  end
  
  def _get_date_by_specific_year_and_month_or_today(year, month)
    action_date = nil
    begin
      unless today.beginning_of_month == Date.new(year.to_i, month.to_i).beginning_of_month
        action_date = Date.new(year.to_i, month.to_i)
      end
    rescue ArgumentError => ex
    end
    action_date || today
  end
  
  #
  # exec adding adjustment
  #
  def _create_adjustment
    Item.transaction do
      item = Item.new
      item.user = @user
      item.year, item.month, item.day = _get_action_year_month_day_from_params
      display_year = params[:year].to_i
      display_month = params[:month].to_i
      @display_year_month = Date.new(display_year, display_month)
      item.name = 'Adjustment'
      item.from_account_id  = -1
      item.to_account_id  = CommonUtil.remove_comma(params[:to]).to_i
      item.is_adjustment = true
      item.tag_list = params[:tag_list]
      item.user_id = item.user.id
      begin
        item.adjustment_amount = _calc_amount(params[:adjustment_amount])
      rescue SyntaxError
        render_rjs_error :id => "warning", :default_message => _("Amount is invalid.")
        return
      end

      # 一旦、ここでvalidateを実行しておく(action_date等が他の箇所で参照されているため)
      item.amount = 0 #ダミーデータ(validateのため)
      unless item.valid?
        render_rjs_error(:id => "warning", :errors => item.errors, :default_message => _('Input value is incorrect'))
        return
      end
      item.amount = nil #ダミーデータの除去

      # すでに同日かつ同account_idの残高調整が存在しないかチェックし、存在する場合は削除する
      prev_adj = @user.items.find_by_to_account_id_and_action_date_and_is_adjustment(item.to_account_id, item.action_date, true)
      unless prev_adj.nil?
        MonthlyProfitLoss.reflect_relatively(@user,
                           prev_adj.action_date.beginning_of_month,
                           -1,
                           prev_adj.to_account_id,
                           prev_adj.amount * (-1))
        prev_adj.destroy
      end

      # 残高計算(amountの決定)
      # amountの算出
      # 前月までのassetを算出
      asset = @user.accounts.asset(@user, item.to_account_id, item.action_date)
      item.amount = item.adjustment_amount - asset
      @item = item
      
      item.save!
      MonthlyProfitLoss.reflect_relatively(@user,
                                           item.action_date.beginning_of_month,
                                           -1,
                                           item.to_account_id,
                                           item.amount)
      # 未来の残高調整を再調整
      Item.adjust_future_balance(@user, item.to_account_id, item.amount * (-1), item.action_date, item.id)
      if item.action_date.beginning_of_month == Date.new(display_year, display_month)
        items = _get_items(item.action_date.year, item.action_date.month)
      end

      render :update do |page|

        page[:warning].set_style :color => 'blue'
        page.replace_html :warning, _('Item was added successfully.') + ' ' + item.action_date.strftime("%Y/%m/%d") + ' ' + _('Adjustment') + ' ' + CommonUtil.separate_by_comma(item.adjustment_amount) + _('yen')
        if item.action_date.beginning_of_month == Date.new(display_year, display_month)
          page.replace_html :items, ''
          items.each do |it|
            page.insert_html :bottom, :items, render_item(it)
          end
          page.insert_html :bottom, :items, :partial=>'remains_link'
          page.select('#item_' + item.id.to_s + ' div').each do |etty|
            etty.visual_effect :highlight, :duration => HIGHLIGHT_DURATION
          end
        end
      end
    end
  rescue ActiveRecord::RecordInvalid
    render_rjs_error(:id => "warning", :errors => item.errors, :default_message => _('Input value is incorrect'))
  end

  #
  # exec adding item.
  #
  def _create_entry
    item = nil
    Item.transaction do
      year, month, day = _get_action_year_month_day_from_params
      name  = params[:item_name]
      amount = 0
      only_add = params[:only_add]
      from  = params[:from].to_i
      to  = params[:to].to_i
      confirmation_required = params[:confirmation_required]
      tag_list = params[:tag_list]
      unless only_add
        display_year = params[:year].to_i
        display_month = params[:month].to_i
        @display_year_month = Date.new(display_year, display_month)
      end

      begin
        amount = _calc_amount(params[:amount])
      rescue SyntaxError
        render_rjs_error :id => "warning", :default_message => _("Amount is invalid.")
        return
      end

      item, affected_items, is_error =
        Teller.create_entry(:user => @user,
                            :name => name,
                            :from_account_id => from.to_i,
                            :to_account_id => to.to_i,
                            :amount => amount,
                            :action_date => Date.new(year,month,day),
                            :confirmation_required => confirmation_required,
                            :tag_list => tag_list)
      if is_error
        raise ActiveRecord::RecordInvalid.new(item)
      end
      # 以下、表示処理
      item_month = Date.new(year, month, 1)
      # displaying page from here
      @renderer_queues ||= []
      if only_add
        @renderer_queues += renderer_queues_for_create_entry_simple(item)
      else
        if item_month == @display_year_month
          @items = _get_items(item_month.year, item_month.month)
        end
        
        @renderer_queues += renderer_queues_for_create_entry(item, @items)
      end
    end # transaction
    render "common/rjs_queue_renderer.rjs"
  rescue ActiveRecord::RecordInvalid
    render_rjs_error(:id => "warning", :errors => (item.nil? ? nil : item.errors), :default_message => _('Input value is incorrect'))
  end

  def renderer_queues_for_create_entry_simple(item)
    ques = []

app/helpers/api/entries_helper.rb
module Api::EntriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  
end

app/views/entries/_account_status_blank.html.erb
<div id="account_status_explain" class="drawer"><%= link_to "<span id='account_status_icon'>◆</span> <span id='account_status_loading' style ='display: none;'>#{ image_tag('loading.gif', :alt=>'loading...', :border => 0, :height => 12, :width => 12) }</span> 今日(#{ today.strftime('%m/%d') })の状況".html_safe, account_status_path, :method => :get, :before => "$('account_status_icon').hide(); $('account_status_loading').show();", :remote => true %></div>

app/views/entries/_add_adjustment.html.erb
<p id="add_item_explain"><%= _('Adjustment') %> <span style='font-weight: normal;font-size: 12px;'><%= link_to _('Register Income/Outgo'), new_entry_path(:year => date.year, :month => date.month), :remote => true, :method => :get %></span></p>
<%= form_tag entries_path(date.year, date.month), :remote => true, :method => :post, :before=>"$('new_add_button').disabled = true", :complete=>"$('do_add_item').adjustment_amount.value = '';$('new_add_button').disabled = false", :id=>'do_add_item' do -%>
<%= text_field_tag :action_year, date.year, :size=>5 %>/<%= text_field_tag :action_month, date.month, :size=>3 %>/<%= text_field_tag :action_day, (today.year == date.year && today.month == date.month) ? today.day : nil, :size=>3 %> <%= _("Select an account to adjust amount.") %><br/>
<%= select_tag 'to', options_for_select(@separated_accounts[:bank_accounts]) %> <%= _('Balance:') %><%= text_field_tag 'adjustment_amount', nil, :size=>10, :style=>"text-align: right;" %><%= _("yen") %><br/>
タグ <%= text_field_tag 'tag_list' -%> <%= submit_tag _('Register'), :id=>'new_add_button' %><%= hidden_field_tag 'entry_type', 'adjustment' -%>
<% end -%>

app/views/entries/_add_item.html.erb
<p id="add_item_explain"><%= _("Register Income/Outgo") %> <span style='font-weight: normal;font-size: 12px;'><%= link_to _('Register Adjustment'), new_entry_path(:year => it.action_date.year, :month => it.action_date.month, :entry_type => 'adjustment'), :remote => true, :method => :get %></span></p>
<%= form_tag entries_path(it.action_date.year, it.action_date.month), :remote => true, :method => :post, :before=>"$('new_add_button').disabled = true", :complete=>"$('new_add_button').disabled = false", :id=>'do_add_item' do -%>
<%= text_field_tag :action_year, it.action_date.year, :size=>5 %>/<%= text_field_tag :action_month, it.action_date.month, :size=>3 %>/<%= text_field_tag :action_day, (it.action_date.year == today.year && it.action_date.month == today.month) ? it.action_date.day : nil, :size=>3, :placeholder=>_('Day') %> <%= text_field_tag :item_name, it.name, :size=>30, :placeholder=>_('Input explanation') %>
<%= check_box_tag :confirmation_required, true, it.confirmation_required? %><%= link_to '要確認', mark_entries_path('confirmation_required') %>
<div id="candidates"></div>
<%= select_tag 'from', options_for_select(@separated_accounts[:from_accounts], it.from_account_id.to_s) %>=&gt;<%= select_tag 'to', options_for_select(@separated_accounts[:to_accounts], it.to_account_id.to_s) %> <%= _("Amount:") %><%= text_field_tag 'amount', ((it.amount.nil? || it.amount == 0) ? nil : CommonUtil.separate_by_comma(it.amount)), :size=>10, :style=>"text-align: right;", :placeholder=>_('amount') %><%= _("yen") %><br/>
タグ <%= text_field_tag 'tag_list' -%> <%= submit_tag _('Register'), :id=>'new_add_button'  %>
<script type="text/javascript"> 
//<![CDATA[
new Form.Element.Observer('item_name', 1, function(element, value) {new Ajax.Updater('candidates', '<%= entry_candidates_path %>', {asynchronous:true, evalScripts:true, method:'get', parameters:'item_name=' + encodeURIComponent(value)})})
//]]>
</script>
<% end -%>

app/views/entries/_edit_adjustment.html.erb
<div id="item_<%= item.id %>" class="item">
<%= form_tag entry_path(params[:year].to_i, params[:month].to_i, item.id), :remote => true, :method => :put,  :before=>"$('edit_button_#{item.id.to_s}').disabled = true;$('item_operation_#{item.id}').hide();$('item_operation_loading_#{item.id}').show();" do -%>
<%= hidden_field_tag :action_year, item.action_date.year -%><%=h item.action_date.year -%>年 <%= hidden_field_tag :action_month, item.action_date.month %><%=h item.action_date.month -%>月 <%= hidden_field_tag :action_day, item.action_date.mday -%><%=h item.action_date.mday -%>日 口座と残高を入力すると、過不足分が自動計算されます。<br/>
<%= select_tag 'to', options_for_select(@separated_accounts[:to_accounts], item.to_account_id.to_s) %> 残高:<%= text_field_tag 'adjustment_amount', item.adjustment_amount, :size=>10, :style=>"text-align: right;" %>円<br/>
タグ <%= text_field_tag 'tag_list', item.tag_list(@user) -%> <span id="item_operation_<%=h item.id %>"><%= submit_tag '変更', :id=>'edit_button_' + item.id.to_s %>
<%= link_to 'キャンセル', entry_path(params[:year].to_i, params[:month].to_i, item.id), :remote => true, :method => :get, :before => "$('item_operation_#{item.id}').hide();$('item_operation_loading_#{item.id}').show();" %></span><span id="item_operation_loading_<%=h item.id %>" style="display:none;"><%= image_tag "loading.gif", :alt => "loading..." %></span><%= hidden_field_tag 'entry_type', 'adjustment' -%>
<% end -%><br/><span id="item_warning_<%= item.id %>" class="warning"></span></div>

app/views/entries/_edit_item.html.erb
<div id="item_<%= item.id %>" class="item">
<%= form_tag entry_path(params[:year].to_i, params[:month].to_i, item.id), :remote => true, :method => :put, :before=>"$('edit_button_#{item.id.to_s}').disabled = true;$('item_operation_#{item.id}').hide();$('item_operation_loading_#{item.id}').show();" do -%>
<%= text_field_tag :action_year, item.action_date.year, :size=>5 %>年 <%= text_field_tag :action_month, item.action_date.month, :size=>3 %>月 <%= text_field_tag :action_day, item.action_date.mday, :size=>3 %>日 <%= text_field_tag :item_name, item.name, :size=>30%>
<%= check_box_tag 'confirmation_required', true, item.confirmation_required? %>要確認
<br/>
<%= select_tag 'from', options_for_select(@separated_accounts[:from_accounts], item.from_account_id.to_s) %>=&gt;<%= select_tag 'to', options_for_select(@separated_accounts[:to_accounts], item.to_account_id.to_s) %> 金額:<%= text_field_tag 'amount', item.amount, :size=>10, :style=>"text-align: right;" %>円<br/>
タグ <%= text_field_tag 'tag_list', item.tag_list(@user) -%> <span id="item_operation_<%=h item.id %>"><%= submit_tag '変更', :id=>'edit_button_' + item.id.to_s %> <%= link_to 'キャンセル', entry_path(params[:year].to_i, params[:month].to_i, item.id), :remote => true, :method => :get, :before => "$('item_operation_#{item.id}').hide();$('item_operation_loading_#{item.id}').show();" %></span><span id="item_operation_loading_<%=h item.id %>" style="display:none;"><%= image_tag "loading.gif", :alt => "loading..." %></span>
<% end -%><br/><span class="warning" id="item_warning_<%= item.id %>"></span></div>

app/views/entries/_item.html.erb
<div id="item_<%= event_item.id %>" class="item">

<% if event_item.is_adjustment? %>

<div class="item_date item_adjustment"><%=h event_item.action_date.strftime("%Y/%m/%d") %></div>
<div class="item_name item_adjustment">残高調整 <%=h CommonUtil.separate_by_comma(event_item.adjustment_amount) %>円
<% if event_item.tags.size > 0 %>
[ <%  event_item.tags.each do |tag|
%><%= link_to_tag(tag) %> <%
  end
%>]<%
end
%>
</div>
<div class="item_from item_adjustment"><%= (event_item.amount < 0) ? colored_account_name(event_item.to_account_id) : '(調整)'%></div>
<div class="item_to item_adjustment"><%= (event_item.amount >= 0) ? colored_account_name(event_item.to_account_id) : '(調整)'%></div>
<div class="item_amount item_adjustment"><%=h CommonUtil.separate_by_comma(event_item.amount.abs) %>円</div>
<div class="item_operation item_adjustment"><span id="navi_<%=h event_item.id %>"><% if @tag || @mark %><%= link_to "表示", entries_path(event_item.action_date.year, event_item.action_date.month) + "#item_#{event_item.id}" %><% else %><%= link_to "編集", edit_entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :method => :get, :remote => true %><br/><%= link_to "削除", entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :method => :delete, :remote => true, :confirm => '本当に削除しますか?' %><% end %></span><span id="loading_<%=h event_item.id %>"  style="display: none;"><%= image_tag "loading.gif", :alt => "loading..." %></span></div>

<% elsif not event_item.parent_id.nil? %>

<div class="item_date item_move"><%= event_item.action_date.strftime("%Y/%m/%d") %></div>
<div class="item_name item_move"><%= event_item.parent_item.confirmation_required? ? link_to('★', entry_confirmation_required_path(event_item.id, :confirmation_required => 'false'), :remote => true, :method => 'put', :class => 'item_confirmation_required') : link_to('☆', entry_confirmation_required_path(event_item.id, :confirmation_required => 'true'), :remote => true, :method => 'put', :class => 'item_confirmation_not_required') %>入金 (<%= link_to event_item.parent_item.action_date.strftime("%y/%m/%d") + ' ' + event_item.parent_item.name, url_for(:controller => 'main', :action=>'show_parent_child_item', :id=>event_item.id, :type=>'parent'), :remote => true %>)
<% if event_item.tags.size > 0 %>
[ <%  event_item.tags.each do |tag|
%><%= link_to_tag(tag) %> <%
  end
%>]<%
end
%>
</div>
<div class="item_from item_move"><%= colored_account_name(event_item.from_account_id) %></div>
<div class="item_to item_move"><%= colored_account_name(event_item.to_account_id) %></div>
<div class="item_amount item_move"><%=h CommonUtil.separate_by_comma(event_item.amount) %>円</div>
<div class="item_operation item_move"></div>

<% elsif not event_item.child_id.nil? %>

<%
if (@separated_accounts[:income_ids]).include?(event_item.from_account_id)
        item_css_class = " item_income"
elsif @separated_accounts[:account_ids].include?(event_item.from_account_id) && @separated_accounts[:account_ids].include?(event_item.to_account_id)
        item_css_class = " item_move"
else
        item_css_class = ""
end
%>
<div class="item_date<%= item_css_class %>"><%= event_item.action_date.strftime("%Y/%m/%d") %></div>
<div class="item_name<%= item_css_class %>"><%= event_item.confirmation_required? ? link_to('★', entry_confirmation_required_path(event_item.id, :confirmation_required => 'false'), :remote => true, :method => 'put', :class => 'item_confirmation_required') : link_to('☆', entry_confirmation_required_path(event_item.id, :confirmation_required => 'true'), :remote => true, :method => 'put', :class => 'item_confirmation_not_required') %><%=h event_item.name %> (<%= link_to event_item.child_item.action_date.strftime("%y/%m/%d") + ' 入金', url_for(:controller => 'main', :action=>'show_parent_child_item', :id=>event_item.id, :type=>'child'), :remote => true %>)
<% if event_item.tags.size > 0 %>
[ <%  event_item.tags.each do |tag|
%><%= link_to_tag(tag) %> <%
  end
%>]<%
end
%>
</div>
<div class="item_from<%= item_css_class %>"><%= colored_account_name(event_item.from_account_id) %></div>
<div class="item_to<%= item_css_class %>"><%= colored_account_name(event_item.to_account_id) %></div>
<div class="item_amount<%= item_css_class %>"><%= CommonUtil.separate_by_comma(event_item.amount) %>円</div>
<div class="item_operation<%= item_css_class %>"><span id="navi_<%=h event_item.id %>"><% if @tag || @mark %><%= link_to "表示", entries_path(event_item.action_date.year, event_item.action_date.month) + "#item_#{event_item.id}" %><% else %><%= link_to "編集", edit_entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :remote => true, :method => :get %> <%= link_to "削除", entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :remote => true, :method => :delete, :confirm => '本当に削除しますか?' %><% end %></span><span id="loading_<%=h event_item.id %>"  style="display: none;"><%= image_tag "loading.gif", :alt => "loading..." %></span></div>

<% else %>
<%
  if (@separated_accounts[:income_ids]).include?(event_item.from_account_id)
    item_css_class = " item_income"
  elsif @separated_accounts[:account_ids].include?(event_item.from_account_id) && @separated_accounts[:account_ids].include?(event_item.to_account_id)
    item_css_class = " item_move"
  else
    item_css_class = ""
  end
%>
<div class="item_date<%= item_css_class %>"><%= event_item.action_date.strftime("%Y/%m/%d") %></div>
<div class="item_name<%= item_css_class %>"><%= event_item.confirmation_required? ? link_to('★', entry_confirmation_required_path(event_item.id, :confirmation_required => 'false'), :remote => true, :method => 'put', :class => 'item_confirmation_required') : link_to('☆', entry_confirmation_required_path(event_item.id, :confirmation_required => 'true'), :remote => true, :method => 'put', :class => 'item_confirmation_not_required') %><%= event_item.name %>
<% if event_item.tags.size > 0 %>
[ <%  event_item.tags.each do |tag|
%><%= link_to_tag(tag) %> <%
  end
%>]<%
end
%>
</div>
<div class="item_from<%= item_css_class %>"><%= colored_account_name(event_item.from_account_id) %></div>
<div class="item_to<%= item_css_class %>"><%= colored_account_name(event_item.to_account_id) %></div>
<div class="item_amount<%= item_css_class %>"><%=h CommonUtil.separate_by_comma(event_item.amount) %>円</div>
<div class="item_operation<%= item_css_class %>"><span id="navi_<%=h event_item.id %>"><% if @tag || @mark %><%= link_to "表示", entries_path(event_item.action_date.year, event_item.action_date.month) + "#item_#{event_item.id}" %><% else %><%= link_to "編集", edit_entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :remote => true, :method => :get %><br/><%= link_to "削除", entry_path(event_item.action_date.year, event_item.action_date.month, event_item.id), :remote => true, :method => :delete, :confirm => '本当に削除しますか?' %><% end %></span><span id="loading_<%=h event_item.id %>"  style="display: none;"><%= image_tag "loading.gif", :alt => "loading..." %></span></div>

<% end %>

</div>
<div class="reset"></div>

app/views/entries/_remains_link.html.erb
<div id='remains' class="item_remains"><span id='remains_operation'>
<% if @tag -%>
<%= link_to _('>> Show All'), tag_entries_path(:tag => @tag, :remaining => true), :remote => true, :method => :get, :before => "$('remains_operation').hide();$('remains_loading').show();" %>
<% elsif @mark -%>
<%= link_to _('>> Show All'), mark_entries_path(:mark => @mark, :remaining => true), :remote => true, :method => :get, :before => "$('remains_operation').hide();$('remains_loading').show();" %>
<% else -%>
<%= link_to _('>> Show All'), entries_path(:year => @display_year_month.year, :month => @display_year_month.month, :remaining => true), :remote => true, :method => :get, :before => "$('remains_operation').hide();$('remains_loading').show();" %>
<% end -%></span><span id='remains_loading' style="display:none;"><%= image_tag "loading.gif", :alt => "loading..." %></span>
</div><!-- remains -->