config/routes.rb
Kakeibo3::Application.routes.draw do

  root :to => "login#login"

  match 'simple', :to => 'entries#new', :entry_type => 'simple', :as => 'simple_input'
  match 'login' => 'login#login', :as => :login
  match 'logout' => 'login#do_logout', :as => :logout
  
  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  resources :entries, :path_prefix => 'current', :as => 'current_entries'
  resources :profit_losses, :path_prefix => 'current',:as => 'current_profit_losses'
  resources :balance_sheets, :path_prefix => 'current', :as => 'current_balance_sheets'
  
  tag_base = '/tags/:tag'
  resources :entries, :path_prefix => tag_base, :as => 'tag_entries'
  mark_base = '/marks/:mark'
  resources :entries, :path_prefix => mark_base, :as => 'mark_entries'

  resources :entries do
    resource :confirmation_required
  end
  
  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

    
  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :assets
    resources :budgets
    scope ':year_month' do
      resources :entries
    end
  end
  
  match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_menu.html.erb
<% if params[:year].blank? || params[:month].blank? 
      e_path = current_entries_path
      pl_path = current_profit_losses_path
      bs_path = current_balance_sheets_path
   else 
      e_path = entries_path(params[:year], params[:month]) 
      pl_path = profit_losses_path(params[:year], params[:month]) 
      bs_path = balance_sheets_path(params[:year], params[:month]) 
   end -%>
<%= params[:controller] == 'entries' ? link_to(_('items'), e_path, {:style=>'background: white none repeat-x scroll 0 0;'}) : link_to(_('items'),e_path) -%>
<%= params[:controller] == 'profit_losses' ? link_to(_('Profit/Loss'), pl_path, {:style=>'background: white none repeat-x scroll 0 0;'}) : link_to(_('Profit/Loss'),pl_path) -%>
<%= params[:controller] == 'balance_sheets' ? link_to(_('Balance'), bs_path, {:style=>'background: white none repeat-x scroll 0 0;'}) : link_to(_('Balance'), bs_path)  -%>
<%= link_to _('Configuration'), settings_accounts_path -%>
<%= link_to _('Simple Input'), new_current_entry_path(:entry_type=>'simple') -%>
<%= link_to _('Logout'), logout_path, {:confirm=>_('Do you really logout now?')} -%>